# Generated by Django 6.0.3 on 2026-03-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotterySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('government', 'Government'), ('stock', 'Stock'), ('regional', 'Regional'), ('special', 'Special'), ('other', 'Other')], default='other', max_length=20)),
                ('timezone', models.CharField(default='Asia/Bangkok', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SourceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('schedule_type', models.CharField(choices=[('weekly_days', 'Weekly Days'), ('monthly_fixed_dates', 'Monthly Fixed Dates'), ('manual', 'Manual'), ('custom', 'Custom')], max_length=30)),
                ('schedule_config', models.JSONField(blank=True, default=dict)),
                ('requires_resolution', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sources.lotterysource')),
            ],
            options={
                'ordering': ['source__code', 'name'],
                'unique_together': {('source', 'name')},
            },
        ),
    ]
