# Generated by Django 6.0.3 on 2026-03-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('period_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('shifted', 'Shifted'), ('scraped', 'Scraped'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual_review', 'Manual Review')], default='pending', max_length=20)),
                ('resolution_method', models.CharField(blank=True, choices=[('schedule_rule', 'Schedule Rule'), ('calendar_scrape', 'Calendar Scrape'), ('manual_override', 'Manual Override'), ('system_inference', 'System Inference')], max_length=30)),
                ('resolution_source_url', models.URLField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('result_published_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_events', to='sources.lotterysource')),
            ],
            options={
                'ordering': ['-scheduled_date', 'source__code'],
                'unique_together': {('source', 'scheduled_date', 'period_code')},
            },
        ),
    ]
